# Generated by Django 3.1 on 2020-08-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200826_1239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Handler',
        ),
    ]
