# Generated by Django 3.1 on 2020-08-26 13:00

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('io', models.CharField(choices=[('I', 'Input Only'), ('O', 'Output Only'), ('D', 'Input / Output')], default='D', max_length=1)),
                ('extension', models.CharField(max_length=100)),
                ('mime_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='1', max_length=100)),
                ('uploaded_file', models.FileField(max_length=200, null=True, upload_to=core.models.File.content_filename)),
                ('format', models.ForeignKey(default='csv', on_delete=django.db.models.deletion.CASCADE, to='core.fileformat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[('M', 'MATLAB Function'), ('P', 'Python Function')], default='M', max_length=1)),
                ('output_format', models.ForeignKey(default='csv', on_delete=django.db.models.deletion.CASCADE, related_name='output_formats', to='core.fileformat')),
                ('supported_input', models.ForeignKey(default='csv', on_delete=django.db.models.deletion.CASCADE, related_name='supported_inputs', to='core.fileformat')),
            ],
        ),
    ]
