# Generated by Django 3.1.1 on 2020-10-28 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201027_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='scripts',
            field=models.ManyToManyField(through='core.Execution', to='core.Script'),
        ),
        migrations.AddField(
            model_name='execution',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='execution',
            name='algorithm',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='execution_algorithm', to='core.algorithm'),
        ),
    ]
