# Generated by Django 3.1.1 on 2020-10-28 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201028_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='execution',
            options={'ordering': ['order']},
        ),
    ]
