# Generated by Django 3.1 on 2020-08-25 20:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200825_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uploaded_file',
            field=models.FileField(max_length=200, null=True, upload_to=core.models.File.content_filename),
        ),
    ]
