# Generated by Django 3.1.1 on 2020-10-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201028_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execution',
            name='data_input',
        ),
        migrations.RemoveField(
            model_name='execution',
            name='data_output',
        ),
    ]
