# Generated by Django 3.1.1 on 2020-10-28 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201028_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='data_input',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='execution_inputs', to='core.file'),
        ),
        migrations.AddField(
            model_name='execution',
            name='data_output',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execution_outputs', to='core.file'),
        ),
    ]
