# Generated by Django 3.1.1 on 2020-10-28 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201028_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='data_input',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execution_inputs', to='core.file'),
        ),
    ]
