# Generated by Django 3.1.1 on 2020-10-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201029_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algorithm',
            options={},
        ),
    ]
