# Generated by Django 3.1.1 on 2020-09-23 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_algorithm_uploaded_algorithm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Algorithm',
            new_name='Subprocess',
        ),
        migrations.RenameField(
            model_name='subprocess',
            old_name='uploaded_algorithm',
            new_name='uploaded_subprocess',
        ),
    ]
