# Generated by Django 3.1.1 on 2020-10-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200923_1249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subprocess',
            new_name='Script',
        ),
        migrations.RenameField(
            model_name='script',
            old_name='uploaded_subprocess',
            new_name='uploaded_script',
        ),
    ]
