# Generated by Django 3.1.1 on 2020-10-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201029_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='scripts',
            field=models.ManyToManyField(related_name='algorithms_related', through='core.Execution', to='core.Script'),
        ),
    ]
