# Generated by Django 3.1.1 on 2020-10-29 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201029_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='data_input',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_inputs', to='core.file'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='data_output',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_outputs', to='core.file'),
        ),
    ]
