# Generated by Django 3.1 on 2020-08-25 17:32

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uploaded_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=''),
        ),
    ]
