# Generated by Django 3.1 on 2020-08-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200825_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uploaded_file',
            field=models.FileField(max_length=200, null=True, upload_to='documents/'),
        ),
    ]
