# Generated by Django 3.1 on 2020-08-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200826_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputtype',
            name='input_file_type',
        ),
        migrations.AddField(
            model_name='inputtype',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='inputtype',
            name='extension',
            field=models.CharField(default='.csv', max_length=10),
        ),
        migrations.AddField(
            model_name='inputtype',
            name='name',
            field=models.CharField(default='CSV', max_length=100),
        ),
    ]
