# Generated by Django 3.1 on 2020-08-26 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200826_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='supported_inputs',
        ),
        migrations.AddField(
            model_name='algorithm',
            name='output_format',
            field=models.ForeignKey(default='csv', on_delete=django.db.models.deletion.CASCADE, related_name='output_formats', to='core.fileformat'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='supported_input',
            field=models.ForeignKey(default='csv', on_delete=django.db.models.deletion.CASCADE, related_name='supported_inputs', to='core.fileformat'),
        ),
        migrations.DeleteModel(
            name='InputType',
        ),
    ]
