# Generated by Django 3.1 on 2020-08-26 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200826_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='output_format',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_formats', to='core.fileformat'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='supported_input',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='supported_inputs', to='core.fileformat'),
        ),
    ]
